# Generated by Django 2.2.1 on 2019-05-17 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190513_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Action Required', 'Action Required'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Action Required', max_length=20)),
                ('approved_time', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_approved_by', to=settings.AUTH_USER_MODEL)),
                ('current_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_current_role', to='accounts.Role')),
                ('intended_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_intended_role', to='accounts.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
