# Generated by Django 2.2.1 on 2019-05-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userrolerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrolerequest',
            old_name='approved_time',
            new_name='action_time',
        ),
        migrations.RenameField(
            model_name='userrolerequest',
            old_name='approved_by',
            new_name='actioned_by',
        ),
        migrations.AddField(
            model_name='userrolerequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
