# Generated by Django 2.2.1 on 2019-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190525_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolerequest',
            name='status',
            field=models.SmallIntegerField(choices=[(100, 'Action Required'), (200, 'Approved'), (300, 'Rejected'), (500, 'Deleted')], default=100),
        ),
    ]
