# Generated by Django 2.2.1 on 2019-06-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwfjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparameter',
            name='date',
            field=models.DateField(),
        ),
    ]
