# Generated by Django 2.2.1 on 2019-06-21 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwfjob', '0002_auto_20190621_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparameter',
            name='image_names',
            field=models.CharField(default='000000', max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_image_names', message='Must be a 6 digit code', regex='^[0-9]{6}$')]),
            preserve_default=False,
        ),
    ]
