# Generated by Django 2.2.1 on 2019-07-08 16:16

from django.db import migrations, models
import dwfjob.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dwfjob', '0003_jobparameter_image_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparameter',
            name='date',
            field=models.CharField(max_length=6, validators=[dwfjob.validators.validate_yymmdd_date]),
        ),
        migrations.AlterField(
            model_name='jobparameter',
            name='mary_run_template',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[dwfjob.validators.validate_yymmdd_date]),
        ),
        migrations.AlterField(
            model_name='jobparameter',
            name='template_date',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[dwfjob.validators.validate_yymmdd_date]),
        ),
    ]
