# Generated by Django 2.2.1 on 2019-11-25 03:17

from django.db import migrations, models
import dwfjob.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dwfjob', '0004_auto_20190709_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparameter',
            name='run_dates',
            field=models.CharField(default=None, max_length=2048, validators=[dwfjob.validators.validate_cs_yymmdd_dates]),
            preserve_default=False,
        ),
    ]
