# Generated by Django 2.2.1 on 2019-11-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwfjob', '0005_jobparameter_run_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparameter',
            name='template',
            field=models.CharField(choices=[('make_template', 'Make Template'), ('old_template', 'Old Template'), ('new_template', 'New Template')], default='new_template', max_length=20),
        ),
    ]
