# Generated by Django 2.2.1 on 2019-12-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwfjob', '0007_jobparameter_template_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparameter',
            name='last_mary_run',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
