# Generated by Django 2.2.10 on 2021-08-12 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwfjob', '0011_auto_20200714_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparameter',
            name='image_names',
            field=models.CharField(max_length=2048, validators=[django.core.validators.RegexValidator(code='invalid_image_names', message='Must be comma separated 6/7 digit codes', regex='^(\\d{6}|\\d{7})(\\s*,\\s*(\\d{6}|\\d{7}))*$')]),
        ),
    ]
